### ISSUE TITLE
Ensure that docstrings pass numpydoc validation

### ISSUE THREAD

**Issue by LilianBoulard** [dirty-cat/dirty_cat#345]
### Background / Objective

[Docstrings](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring) in Python are string literals that occur as the first statement in a module, function, class, or method definition.

These are some of the characteristics of a docstring:

- Triple quotes are used to encompass the docstring text.
- There is no blank line before or after the docstring.
- The docstring is a phrase ending in a period.
- [more details](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring)

[numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) is one set of criteria to check for consistent documentation structure.

### Validating docstrings in dirty_cat

To ensure consistent documentation structure in dirty_cat, we are using numpydoc validation. Currently, documentation tests are failing for various functions. As a temporary fix, we have suppressed error messages in [test_docstrings.py](https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/tests/test_docstrings.py). Many of the functions in dirty_cat need to be updated to comply with numpy docstring validation. In the below issue, we provide step-by-step instructions on how contributors can test and update functions.

### Steps

1. Make sure you have the development dependencies and documentation dependencies installed (see [the contribution guidelines](https://github.com/dirty-cat/dirty_cat/blob/master/CONTRIBUTING.rst)).
2. Pick a function/class from the list below and leave a comment saying you are going to work on it. This way we can keep track of what everyone is working on.
2.1 Make sure you've created a separate branch from main before editing files for your new contribution. Refer to our [contributing guidelines](https://github.com/dirty-cat/dirty_cat/blob/master/CONTRIBUTING.rst) for more information.
3. Remove the function from the list `DOCSTRING_TEMP_IGNORE_SET` in [`test_docstring.py`](https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/tests/test_docstrings.py#L22).
5. Let's say you picked `dirty_cat.gap_encoder.GapEncoder.fit`, run numpydoc validation as follows.
```commandline
pytest dirty_cat/tests/test_docstrings.py
```

6. If you see the test fails, please fix them by following the recommendation provided by the failing test.
7. If you see all the tests pass, you do not need to do any additional changes.
8. Commit your changes.
9. Open a Pull Request with an opening message Addresses #345. Note that each item should be submitted in a separate Pull Request.
10. Include the function name in the title of the pull request. For example: *"DOC Ensures that GapEncoder.fit passes numpydoc validation"*.

Note: once you have issued 1-2 such PRs, feel free to move on to contributing more complex pull requests that involve more thinking and leave the other fixes to first time contributors for them to learn the github contribution workflow :)

### Functions to Update

- [X] `dirty_cat._datetime_encoder.DatetimeEncoder` #421
- [x] `dirty_cat._datetime_encoder.DatetimeEncoder.fit` #367
- [ ] `dirty_cat._datetime_encoder.DatetimeEncoder.get_feature_names`
- [ ] `dirty_cat._datetime_encoder.DatetimeEncoder.get_feature_names_out`
- [x] `dirty_cat._datetime_encoder.DatetimeEncoder.transform` #368
- [x] `dirty_cat._gap_encoder.GapEncoder` #438 
- [X] `dirty_cat._gap_encoder.GapEncoder.fit` #439 
- [ ] `dirty_cat._gap_encoder.GapEncoder.get_feature_names`
- [ ] `dirty_cat._gap_encoder.GapEncoder.get_feature_names_out`
- [ ] `dirty_cat._gap_encoder.GapEncoder.partial_fit`
- [ ] `dirty_cat._gap_encoder.GapEncoder.score`
- [ ] `dirty_cat._gap_encoder.GapEncoder.transform`
- [ ] `dirty_cat._minhash_encoder.MinHashEncoder`
- [ ] `dirty_cat._minhash_encoder.MinHashEncoder.fit`
- [X] `dirty_cat._minhash_encoder.MinHashEncoder.transform` #439
- [ ] `dirty_cat._similarity_encoder.SimilarityEncoder` #504
- [X] `dirty_cat._similarity_encoder.SimilarityEncoder.fit` #439
- [X] `dirty_cat._similarity_encoder.SimilarityEncoder.transform` #439
- [ ] `dirty_cat._similarity_encoder.SimilarityEncoder.fit_transform`
- [x] `dirty_cat._table_vectorizer.TableVectorizer` #399
- [X] `dirty_cat._table_vectorizer.TableVectorizer.fit_transform` #439
- [ ] `dirty_cat._table_vectorizer.TableVectorizer.transform`
- [ ] `dirty_cat._table_vectorizer.TableVectorizer.get_feature_names`
- [ ] `dirty_cat._table_vectorizer.TableVectorizer.get_feature_names_out`
- [ ] `dirty_cat._target_encoder.TargetEncoder`
- [X] `dirty_cat._target_encoder.TargetEncoder.fit` #439
- [X] `dirty_cat._target_encoder.TargetEncoder.transform` #439
- [ ] `dirty_cat._fuzzy_join.fuzzy_join`

**Comment by alexdt1982** [comment]
Hi, can I work on this? Looking to make my first open source contribution.

**Comment by GaelVaroquaux** [comment]
Hi, thank you very much for stepping up.

It would be great to have you help. You can pick one function and submit a first pull request. It's good to iterate from a simple contribution in order to learn the process.

**Comment by alexdt1982** [comment]
Alright thanks. I'll be working on DatetimeEncoder.fit.

**Comment by alexdt1982** [comment]
For some reason when I run pytest it exits with no errors but collects 0 items. Should I change the name of the file/function to begin with "test"?

**Comment by alexdt1982** [comment]
Having trouble doing numpydoc bc of issue mentioned above. Can someone please help?

**Comment by LilianBoulard** [comment]
Hi @alexdt1982
Thanks for the heads up, it was an issue with the test itself. I fixed it and it should work now!
Don't forget to fetch the commits added in the master branch (`pull master`). I've also updated the comment above :)

**Comment by LilianBoulard** [comment]
I'll be working on the `TargetEncoder`

**Comment by alexdt1982** [comment]
Validated DatetimeEncoder.fit. but getting this issue when I try to commit @LilianBoulard @GaelVaroquaux.
![Screenshot (143)](https://user-images.githubusercontent.com/77065772/190481020-7f1b9728-ee2f-496d-a274-e99dc5dd64ad.png)

**Comment by LilianBoulard** [comment]
Yes, this is a Windows-specific issue, but both Gaël and I work on linux-based distributions. Search for solutions on Stack Overflow, you'll most likely find help there. If you have issues related to dirty_cat, we'll be able to help, but this is not one, sorry!

**Comment by alexdt1982** [comment]
It's ok, I found out the issue. Will create a PR soon.

**Comment by alexdt1982** [comment]
Thanks for giving me the opportunity guys. Can I work on validating another function in DatetimeEncoder?

**Comment by GaelVaroquaux** [comment]
> Can I work on validating another function in DatetimeEncoder?

With pleasure! Thanks!

**Comment by alexdt1982** [comment]
Validated DatetimeEncoder.transform.

**Comment by GaelVaroquaux** [comment]
> Hi, can I work on this? Looking to make my first open source contribution.

Yes. We need to break down the issue, and you should tackle a single file.

**Comment by LilianBoulard** [comment]
I'll be working on `dirty_cat._super_vectorizer.SuperVectorizer`

**Comment by myungkim930** [comment]
I'll be working on dirty_cat._datetime_encoder.DatetimeEncoder

**Comment by LilianBoulard** [comment]
I'll be working on the ``GapEncoder``

**Comment by jovan-stojanovic** [comment]
Merging https://github.com/dirty-cat/dirty_cat/pull/439 may resolve some functions.
