### ISSUE TITLE
Improve coverage of main features

### ISSUE THREAD

**Issue by jovan-stojanovic** [dirty-cat/dirty_cat#371]
Here are some of the code coverage results:
``` 
------------------------------------------------------------------------
dirty_cat/_datetime_encoder.py             88%
dirty_cat/_gap_encoder.py                  88%
dirty_cat/_minhash_encoder.py              94%
dirty_cat/_similarity_encoder.py           90%
dirty_cat/_string_distances.py             91%
dirty_cat/_super_vectorizer.py             85%
dirty_cat/_target_encoder.py               78%
dirty_cat/_utils.py                        93%
dirty_cat/datasets/_fetching.py            97%
...
------------------------------------------------------------------------
TOTAL                                     89%
```
It may be good to work on improving those so that we have clear standards on what coverage is needed for new features.

### Tests to Update

- [ ] `dirty_cat._datetime_encoder.DatetimeEncoder`
- [ ] `dirty_cat._gap_encoder.GapEncoder`
- [ ] `dirty_cat/_minhash_encoder.py` #379 
- [ ] `dirty_cat/_similarity_encoder.py`
- [ ] `dirty_cat/_string_distances.py`
- [ ] `dirty_cat/_super_vectorizer.py`
- [ ] `dirty_cat/_target_encoder.py` #375 
- [ ] `dirty_cat/_utils.py`
- [ ] `dirty_cat/datasets/_fetching.py`

**Comment by jeromedockes** [comment]
tablevectorizer & datetimeencoder are at 100% after #902 so we checked those in the list. @TheooJ will open a PR to remove the unused function in _utils.py
