### ISSUE TITLE
Add simple reproducible examples to features

### ISSUE THREAD

**Issue by jovan-stojanovic** [dirty-cat/dirty_cat#373]
Our main encoders and other features are missing simple reproducible examples
that will appear on the website and give a first overview of what the feature can do.

### Examples to add

- [ ] `dirty_cat/_super_vectorizer.py`

- [ ] `dirty_cat._gap_encoder.GapEncoder`
- [ ] `dirty_cat/_minhash_encoder.py`
- [ ] `dirty_cat/_similarity_encoder.py`
- [ ] `dirty_cat/_target_encoder.py`

- [ ] `dirty_cat._datetime_encoder.DatetimeEncoder`
