### ISSUE TITLE
Make our tests more robust to flawky downloads

### ISSUE THREAD

**Issue by GaelVaroquaux** [dirty-cat/dirty_cat#376]
Some tests use data downloaded from internet:
https://github.com/dirty-cat/dirty_cat/blob/master/dirty_cat/tests/test_minhash_encoder.py

As a result, the tests are fragile (see https://github.com/dirty-cat/dirty_cat/actions/runs/3175021096/jobs/5176906979#step:6:907 for instance).

It seems to me that some of these tests could be rewritten on generated data.

### Tests with flawky downloads

- [X] `test_fast_hash.py` #402 
- [X] `test_gap_encoder.py` #401 
- [X] `test_minhash_encoder.py` #379

**Comment by jovan-stojanovic** [comment]
### Tests with flawky downloads

- [ ] `test_fast_hash.py`
- [ ] `test_gap_encoder.GapEncoder`
- [ ] `test_minhash_encoder.py` #379
